[package]
name = "bound"
version = "0.1.0"
edition = "2021"

[dependencies]

indicatif = "0.17.5"
clap = { version = "4.3.0", features = ["derive"] }
git2 = "0.19.0"
chrono = "0.4"
thiserror = "~1"
codeowners = "0.1.3"
anyhow = "1.0.89"

[dev-dependencies]
tempfile = "3.13.0"
