[package]
name = "bound"
version = "0.1.0"
edition = "2021"

[dependencies]

clap = { version = "4.3.0", features = ["derive"] }
chrono = "0.4"
thiserror = "~1"
anyhow = "1.0.89"
tempfile = "3.13.0"
itertools = "0.13.0"
codeowners = "0.1.3"
